fixtures:
  repositories:
    'compliance_markup':
      repo: 'https://github.com/simp/pupmod-simp-compliance_markup'
    'iptables':
      repo: 'https://github.com/simp/pupmod-simp-iptables'
    'stdlib':
      repo: 'https://github.com/simp/puppetlabs-stdlib'
      ref: 'simp-master'
  symlinks:
    memcached: "#{source_dir}"
